import json
import os

cells = [
    {
        'cell_type': 'markdown',
        'metadata': {},
        'source': [
            '# RSNA Knee Abnormality Detection (V2 Baseline)\n',
            '### Upgraded DINOv2 Pipeline: Anatomical Plane Selection, Medical Augmentations, Class-Weighted Loss & 5-Fold Loop'
        ]
    },
    {
        'cell_type': 'code',
        'metadata': {},
        'outputs': [],
        'execution_count': None,
        'source': [
            '# CELL 1: Imports and Global Configuration\n',
            'import os\n',
            'import sys\n',
            'import gc\n',
            'import glob\n',
            'import math\n',
            'import numpy as np\n',
            'import pandas as pd\n',
            'import pydicom\n',
            'from pydicom.pixel_data_handlers.util import apply_voi_lut\n',
            'import cv2\n',
            'from tqdm.auto import tqdm\n',
            'import matplotlib.pyplot as plt\n',
            'import seaborn as sns\n',
            '\n',
            'import torch\n',
            'import torch.nn as nn\n',
            'from torch.utils.data import Dataset, DataLoader\n',
            'import torch.amp\n',
            'from torch.optim import AdamW\n',
            'from torch.optim.lr_scheduler import CosineAnnealingLR\n',
            'from sklearn.model_selection import KFold\n',
            'from sklearn.metrics import roc_auc_score\n',
            'import timm\n',
            'import albumentations as A\n',
            '\n',
            'class CFG:\n',
            '    seed = 42\n',
            '    base_dir = "/kaggle/input/competitions/rsna-knee-abnormality-detection"\n',
            '    if not os.path.exists(base_dir):\n',
            '        base_dir = "/kaggle/input/rsna-knee-abnormality-detection"\n',
            '        \n',
            '    train_csv = os.path.join(base_dir, "train.csv")\n',
            '    train_series_csv = os.path.join(base_dir, "train_series.csv")\n',
            '    train_images_dir = os.path.join(base_dir, "train_series")\n',
            '    \n',
            '    llm_labels_dir = "/kaggle/input/datasets/pilkwang/rsna-knee-llm-labels"\n',
            '    pretrained_weights_dir = "/kaggle/input/datasets/pilkwang/rsna-knee-weights"\n',
            '    \n',
            '    model_name = "vit_small_patch14_reg4_dinov2.lvd142m"\n',
            '    crop_mm = 130.0 \n',
            '    image_size = 336\n',
            '    batch_size = 8\n',
            '    num_workers = 2\n',
            '    epochs = 5\n',
            '    lr = 2e-4\n',
            '    weight_decay = 1e-4\n',
            '    \n',
            '    n_folds = 5\n',
            '    folds_to_train = [0, 1, 2, 3, 4]  # Train all 5 folds\n',
            '    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")\n',
            '\n',
            'torch.manual_seed(CFG.seed)\n',
            'np.random.seed(CFG.seed)\n',
            'print(f"Device: {CFG.device} | Base Dir: {CFG.base_dir}")\n'
        ]
    },
    {
        'cell_type': 'code',
        'metadata': {},
        'outputs': [],
        'execution_count': None,
        'source': [
            '# CELL 2: Data Loading & LLM Label Integration\n',
            'train_df = pd.read_csv(CFG.train_csv)\n',
            'train_series_df = pd.read_csv(CFG.train_series_csv)\n',
            'print(f"Loaded raw train.csv: {train_df.shape} | train_series.csv: {train_series_df.shape}")\n',
            '\n',
            'target_cols = [\n',
            '    "ACL", "MCL", "Medial Meniscus", "Lateral Meniscus", \n',
            '    "Medial OA", "Lateral OA", "PF OA", "Effusion", \n',
            '    "Synovitis", "Baker\'s", "Contusion", "Fracture"\n',
            ']\n',
            '\n',
            '# Merge LLM-extracted labels if available\n',
            'llm_candidates = [\n',
            '    os.path.join(CFG.llm_labels_dir, "train.csv"),\n',
            '    os.path.join(CFG.llm_labels_dir, "train_llm_labels.csv"),\n',
            '    os.path.join(CFG.llm_labels_dir, "report_labels_v2.csv")\n',
            ']\n',
            '\n',
            'llm_loaded = False\n',
            'for cand in llm_candidates:\n',
            '    if os.path.exists(cand):\n',
            '        llm_df = pd.read_csv(cand)\n',
            '        print(f"Applying LLM labels from: {cand} ({llm_df.shape})")\n',
            '        train_df.set_index("StudyInstanceUID", inplace=True)\n',
            '        llm_df.set_index("StudyInstanceUID", inplace=True)\n',
            '        train_df.update(llm_df)\n',
            '        train_df.reset_index(inplace=True)\n',
            '        llm_loaded = True\n',
            '        break\n',
            '\n',
            'if not llm_loaded:\n',
            '    print("Notice: Training using direct labels from train.csv")\n',
            '\n',
            'train_df = train_df.dropna(subset=target_cols).reset_index(drop=True)\n',
            'print(f"Total training studies ready: {len(train_df)}")\n',
            '\n',
            '# Compute positive class weights for balanced BCE loss\n',
            'pos_counts = train_df[target_cols].sum().values\n',
            'total_samples = len(train_df)\n',
            'neg_counts = total_samples - pos_counts\n',
            'pos_weights = np.clip(neg_counts / (pos_counts + 1e-5), 1.0, 10.0)\n',
            'pos_weight_tensor = torch.tensor(pos_weights, dtype=torch.float32).to(CFG.device)\n',
            'print(f"Computed Class Weights: {np.round(pos_weights, 2)}")\n'
        ]
    },
    {
        'cell_type': 'code',
        'metadata': {},
        'outputs': [],
        'execution_count': None,
        'source': [
            '# CELL 3: Robust DICOM Geometry & Anatomical Plane Series Selector\n',
            'def select_best_series(study_id, series_df, images_base_dir):\n',
            '    """\n',
            '    Intelligently select the most diagnostically relevant series:\n',
            '    1. Sagittal Fluid-Sensitive\n',
            '    2. Coronal Fluid-Sensitive\n',
            '    3. Any Sagittal/Coronal\n',
            '    4. Any existing series directory\n',
            '    """\n',
            '    study_series = series_df[series_df["StudyInstanceUID"] == study_id]\n',
            '    \n',
            '    # Priority ranking\n',
            '    if len(study_series) > 0:\n',
            '        # Check Sagittal Fluid-Sensitive\n',
            '        if "Anatomical_Plane" in study_series.columns and "Fluid_Sensitive" in study_series.columns:\n',
            '            cand = study_series[(study_series["Anatomical_Plane"] == "Sagittal") & (study_series["Fluid_Sensitive"] == 1)]\n',
            '            if len(cand) == 0:\n',
            '                cand = study_series[(study_series["Anatomical_Plane"] == "Coronal") & (study_series["Fluid_Sensitive"] == 1)]\n',
            '            if len(cand) == 0:\n',
            '                cand = study_series[study_series["Anatomical_Plane"].isin(["Sagittal", "Coronal"])]\n',
            '            if len(cand) > 0:\n',
            '                study_series = cand\n',
            '                \n',
            '        for _, row in study_series.iterrows():\n',
            '            s_dir = os.path.join(images_base_dir, str(study_id), str(row["SeriesInstanceUID"]))\n',
            '            if os.path.exists(s_dir):\n',
            '                return s_dir\n',
            '                \n',
            '    # Fallback to filesystem discovery\n',
            '    study_folder = os.path.join(images_base_dir, str(study_id))\n',
            '    if os.path.exists(study_folder):\n',
            '        subfolders = [os.path.join(study_folder, s) for s in os.listdir(study_folder) if os.path.isdir(os.path.join(study_folder, s))]\n',
            '        if subfolders:\n',
            '            return subfolders[0]\n',
            '        return study_folder\n',
            '    return None\n',
            '\n',
            'def get_slice_position(dcm):\n',
            '    if hasattr(dcm, "ImageOrientationPatient") and hasattr(dcm, "ImagePositionPatient"):\n',
            '        try:\n',
            '            pos = np.array([float(x) for x in dcm.ImagePositionPatient])\n',
            '            ori = np.array([float(x) for x in dcm.ImageOrientationPatient])\n',
            '            normal = np.cross(ori[0:3], ori[3:6])\n',
            '            return np.dot(pos, normal)\n',
            '        except:\n',
            '            pass\n',
            '    if hasattr(dcm, "SliceLocation"): return float(dcm.SliceLocation)\n',
            '    if hasattr(dcm, "InstanceNumber"): return float(dcm.InstanceNumber)\n',
            '    return 0.0\n',
            '\n',
            'def sort_dicom_files(dicom_paths):\n',
            '    metadata = []\n',
            '    for path in dicom_paths:\n',
            '        try:\n',
            '            dcm = pydicom.dcmread(path, stop_before_pixels=True)\n',
            '            metadata.append({"path": path, "pos": get_slice_position(dcm), "instance": getattr(dcm, "InstanceNumber", 0)})\n',
            '        except:\n',
            '            continue\n',
            '    metadata.sort(key=lambda x: (x["pos"], x["instance"], x["path"]))\n',
            '    return [x["path"] for x in metadata]\n',
            '\n',
            'def read_and_crop_dicom(path, crop_mm=130.0, target_size=336):\n',
            '    try:\n',
            '        dcm = pydicom.dcmread(path)\n',
            '        img = apply_voi_lut(dcm.pixel_array, dcm)\n',
            '        if dcm.PhotometricInterpretation == "MONOCHROME1": img = np.amax(img) - img\n',
            '        img = img - np.min(img)\n',
            '        img = img / (np.max(img) + 1e-6)\n',
            '        img = (img * 255).astype(np.uint8)\n',
            '        \n',
            '        spacing_y, spacing_x = 1.0, 1.0\n',
            '        if hasattr(dcm, "PixelSpacing"):\n',
            '            try: spacing_y, spacing_x = [float(s) for s in dcm.PixelSpacing]\n',
            '            except: pass\n',
            '        \n',
            '        h, w = img.shape\n',
            '        crop_h = min(int(crop_mm / spacing_y), h)\n',
            '        crop_w = min(int(crop_mm / spacing_x), w)\n',
            '        start_y, start_x = (h - crop_h) // 2, (w - crop_w) // 2\n',
            '        \n',
            '        cropped_img = img[start_y:start_y+crop_h, start_x:start_x+crop_w]\n',
            '        return cv2.resize(cropped_img, (target_size, target_size), interpolation=cv2.INTER_CUBIC)\n',
            '    except:\n',
            '        return np.zeros((target_size, target_size), dtype=np.uint8)\n'
        ]
    },
    {
        'cell_type': 'code',
        'metadata': {},
        'outputs': [],
        'execution_count': None,
        'source': [
            '# CELL 4: Multi-Slice Dataset with Medical Augmentations\n',
            'train_transform = A.Compose([\n',
            '    A.HorizontalFlip(p=0.5),\n',
            '    A.ShiftScaleRotate(shift_limit=0.05, scale_limit=0.08, rotate_limit=12, p=0.5),\n',
            '    A.RandomBrightnessContrast(brightness_limit=0.15, contrast_limit=0.15, p=0.5),\n',
            '    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225))\n',
            '])\n',
            '\n',
            'val_transform = A.Compose([\n',
            '    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225))\n',
            '])\n',
            '\n',
            'class RSNAKneeDataset(Dataset):\n',
            '    def __init__(self, df, series_df, is_train=True):\n',
            '        self.df = df.reset_index(drop=True)\n',
            '        self.series_df = series_df\n',
            '        self.is_train = is_train\n',
            '        self.target_cols = target_cols\n',
            '        self.transform = train_transform if is_train else val_transform\n',
            '\n',
            '    def __len__(self):\n',
            '        return len(self.df)\n',
            '\n',
            '    def __getitem__(self, idx):\n',
            '        row = self.df.iloc[idx]\n',
            '        study_id = str(row["StudyInstanceUID"])\n',
            '        series_dir = select_best_series(study_id, self.series_df, CFG.train_images_dir)\n',
            '        \n',
            '        sorted_files = []\n',
            '        if series_dir and os.path.exists(series_dir):\n',
            '            dcm_files = [os.path.join(series_dir, f) for f in os.listdir(series_dir) if f.endswith(".dcm")]\n',
            '            if dcm_files:\n',
            '                sorted_files = sort_dicom_files(dcm_files)\n',
            '        \n',
            '        num_triplets = 3\n',
            '        images = []\n',
            '        if len(sorted_files) >= 3:\n',
            '            valid_files = sorted_files[int(len(sorted_files)*0.2):int(len(sorted_files)*0.8)]\n',
            '            if len(valid_files) < 3:\n',
            '                valid_files = sorted_files\n',
            '            anchors = np.linspace(0, len(valid_files)-1, num_triplets, dtype=int)\n',
            '            \n',
            '            for anchor in anchors:\n',
            '                img_R = read_and_crop_dicom(valid_files[max(0, anchor-1)], CFG.crop_mm, CFG.image_size)\n',
            '                img_G = read_and_crop_dicom(valid_files[anchor], CFG.crop_mm, CFG.image_size)\n',
            '                img_B = read_and_crop_dicom(valid_files[min(len(valid_files)-1, anchor+1)], CFG.crop_mm, CFG.image_size)\n',
            '                \n',
            '                rgb_img = self.transform(image=np.stack([img_R, img_G, img_B], axis=-1))["image"]\n',
            '                images.append(torch.tensor(rgb_img, dtype=torch.float32).permute(2, 0, 1))\n',
            '        elif len(sorted_files) > 0:\n',
            '            img = read_and_crop_dicom(sorted_files[0], CFG.crop_mm, CFG.image_size)\n',
            '            rgb_img = self.transform(image=np.stack([img, img, img], axis=-1))["image"]\n',
            '            tensor_img = torch.tensor(rgb_img, dtype=torch.float32).permute(2, 0, 1)\n',
            '            for _ in range(num_triplets):\n',
            '                images.append(tensor_img)\n',
            '                \n',
            '        while len(images) < num_triplets:\n',
            '            images.append(torch.zeros((3, CFG.image_size, CFG.image_size)))\n',
            '        \n',
            '        images_tensor = torch.stack(images)\n',
            '        labels = torch.tensor(row[self.target_cols].values.astype(np.float32))\n',
            '        return images_tensor, labels\n'
        ]
    },
    {
        'cell_type': 'code',
        'metadata': {},
        'outputs': [],
        'execution_count': None,
        'source': [
            '# CELL 5: DINOv2 Backbone Architecture\n',
            'class DINOv2KneeModel(nn.Module):\n',
            '    def __init__(self, model_name=CFG.model_name, num_classes=12):\n',
            '        super().__init__()\n',
            '        self.encoder = timm.create_model(model_name, pretrained=True, num_classes=0, dynamic_img_size=True)\n',
            '        self.head = nn.Sequential(\n',
            '            nn.Dropout(0.3),\n',
            '            nn.Linear(self.encoder.num_features, num_classes)\n',
            '        )\n',
            '\n',
            '    def forward(self, x):\n',
            '        batch_size, num_triplets, c, h, w = x.shape\n',
            '        features = self.encoder(x.view(-1, c, h, w))\n',
            '        logits, _ = torch.max(self.head(features).view(batch_size, num_triplets, -1), dim=1) \n',
            '        return logits\n',
            '\n',
            '# Test instantiate\n',
            'test_model = DINOv2KneeModel().to(CFG.device)\n',
            'dummy_input = torch.randn(2, 3, 3, CFG.image_size, CFG.image_size).to(CFG.device)\n',
            'with torch.no_grad():\n',
            '    out = test_model(dummy_input)\n',
            'print(f"Model successfully verified! Output shape: {out.shape}")\n',
            'del test_model, dummy_input\n',
            'torch.cuda.empty_cache()\n'
        ]
    },
    {
        'cell_type': 'code',
        'metadata': {},
        'outputs': [],
        'execution_count': None,
        'source': [
            '# CELL 6: Training and Validation Functions\n',
            'def train_epoch(model, dataloader, criterion, optimizer, scaler, device):\n',
            '    model.train()\n',
            '    running_loss = 0.0\n',
            '    pbar = tqdm(dataloader, desc="Training", leave=False)\n',
            '    for images, labels in pbar:\n',
            '        images, labels = images.to(device), labels.to(device)\n',
            '        optimizer.zero_grad()\n',
            '        with torch.amp.autocast("cuda"):\n',
            '            logits = model(images)\n',
            '            loss = criterion(logits, labels)\n',
            '        scaler.scale(loss).backward()\n',
            '        scaler.step(optimizer)\n',
            '        scaler.update()\n',
            '        running_loss += loss.item() * images.size(0)\n',
            '        pbar.set_postfix({"loss": f"{loss.item():.4f}"})\n',
            '    return running_loss / len(dataloader.dataset)\n',
            '\n',
            '@torch.no_grad()\n',
            'def valid_epoch(model, dataloader, criterion, device):\n',
            '    model.eval()\n',
            '    running_loss, all_targets, all_preds = 0.0, [], []\n',
            '    for images, labels in tqdm(dataloader, desc="Validation", leave=False):\n',
            '        images, labels = images.to(device), labels.to(device)\n',
            '        with torch.amp.autocast("cuda"):\n',
            '            logits = model(images)\n',
            '            loss = criterion(logits, labels)\n',
            '        running_loss += loss.item() * images.size(0)\n',
            '        all_targets.append(labels.cpu().numpy())\n',
            '        all_preds.append(torch.sigmoid(logits).cpu().numpy())\n',
            '        \n',
            '    all_targets = np.vstack(all_targets)\n',
            '    all_preds = np.vstack(all_preds)\n',
            '    \n',
            '    # Binarize targets for metric calculation\n',
            '    binary_targets = (all_targets >= 0.5).astype(int)\n',
            '    auc_scores = []\n',
            '    for i in range(12):\n',
            '        if len(np.unique(binary_targets[:, i])) > 1:\n',
            '            auc_scores.append(roc_auc_score(binary_targets[:, i], all_preds[:, i]))\n',
            '            \n',
            '    mean_auc = np.mean(auc_scores) if auc_scores else 0.5\n',
            '    return running_loss / len(dataloader.dataset), mean_auc\n'
        ]
    },
    {
        'cell_type': 'code',
        'metadata': {},
        'outputs': [],
        'execution_count': None,
        'source': [
            '# CELL 7: 5-Fold Training Orchestrator\n',
            'kf = KFold(n_splits=CFG.n_folds, shuffle=True, random_state=CFG.seed)\n',
            'train_df["fold"] = -1\n',
            'for fold, (train_idx, val_idx) in enumerate(kf.split(train_df)):\n',
            '    train_df.loc[val_idx, "fold"] = fold\n',
            '\n',
            'print("Fold distribution:")\n',
            'print(train_df["fold"].value_counts().sort_index())\n',
            '\n',
            'criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight_tensor)\n',
            '\n',
            'for fold in CFG.folds_to_train:\n',
            '    print(f"\\n{\'=\'*50}\\n========== STARTING FOLD {fold} ==========\\n{\'=\'*50}")\n',
            '    \n',
            '    train_split_df = train_df[train_df["fold"] != fold].reset_index(drop=True)\n',
            '    val_split_df = train_df[train_df["fold"] == fold].reset_index(drop=True)\n',
            '    \n',
            '    train_loader = DataLoader(\n',
            '        RSNAKneeDataset(train_split_df, train_series_df, is_train=True),\n',
            '        batch_size=CFG.batch_size,\n',
            '        shuffle=True,\n',
            '        num_workers=CFG.num_workers,\n',
            '        pin_memory=True\n',
            '    )\n',
            '    val_loader = DataLoader(\n',
            '        RSNAKneeDataset(val_split_df, train_series_df, is_train=False),\n',
            '        batch_size=CFG.batch_size,\n',
            '        shuffle=False,\n',
            '        num_workers=CFG.num_workers,\n',
            '        pin_memory=True\n',
            '    )\n',
            '    \n',
            '    model = DINOv2KneeModel().to(CFG.device)\n',
            '    optimizer = AdamW(model.parameters(), lr=CFG.lr, weight_decay=CFG.weight_decay)\n',
            '    scheduler = CosineAnnealingLR(optimizer, T_max=CFG.epochs, eta_min=1e-6)\n',
            '    scaler = torch.amp.GradScaler("cuda")\n',
            '    \n',
            '    best_auc = 0.0\n',
            '    save_path = f"dinov2_knee_fold{fold}_best.pth"\n',
            '    \n',
            '    for epoch in range(CFG.epochs):\n',
            '        train_loss = train_epoch(model, train_loader, criterion, optimizer, scaler, CFG.device)\n',
            '        val_loss, val_auc = valid_epoch(model, val_loader, criterion, CFG.device)\n',
            '        scheduler.step()\n',
            '        \n',
            '        print(f"Fold {fold} | Epoch {epoch+1}/{CFG.epochs} -> Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f} | Val AUC: {val_auc:.4f}")\n',
            '        \n',
            '        if val_auc > best_auc:\n',
            '            best_auc = val_auc\n',
            '            torch.save(model.state_dict(), save_path)\n',
            '            print(f"--> Saved new best model for Fold {fold} (AUC: {best_auc:.4f})")\n',
            '            \n',
            '    print(f"Fold {fold} Complete! Best Validation AUC: {best_auc:.4f}")\n',
            '    del model, optimizer, scheduler, train_loader, val_loader\n',
            '    torch.cuda.empty_cache()\n',
            '    gc.collect()\n'
        ]
    }
]

notebook = {
    'cells': cells,
    'metadata': {
        'kernelspec': {
            'display_name': 'Python 3',
            'language': 'python',
            'name': 'python3'
        }
    },
    'nbformat': 4,
    'nbformat_minor': 5
}

os.makedirs('C:/Users/ahmed/projects/rsna/notebooks', exist_ok=True)
with open('C:/Users/ahmed/projects/rsna/notebooks/RSNA_Knee_DINOv2_Baseline.ipynb', 'w') as f:
    json.dump(notebook, f, indent=2)

print("V2 Training Baseline successfully written and generated!")
