import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "id": "intro",
   "metadata": {},
   "source": [
    "# RSNA Knee Abnormality Detection: DINOv2 Inference\n",
    "This notebook loads the 5 fine-tuned DINOv2 models from our training pipeline, processes the hidden test set DICOMs using our physical-geometry cropping engine, and creates an ensembled `submission.csv`.\n",
    "\n",
    "**⚠️ IMPORTANT:** You must turn **Internet OFF** in the Kaggle right-side panel for this submission to work!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "imports",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import gc\n",
    "import glob\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import cv2\n",
    "import pydicom\n",
    "from pydicom.pixel_data_handlers.util import apply_voi_lut\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "import timm\n",
    "import albumentations as A\n",
    "from albumentations.pytorch import ToTensorV2\n",
    "\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print(f\"Using device: {device}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "config",
   "metadata": {},
   "outputs": [],
   "source": [
    "class CFG:\n",
    "    # Test Data Paths\n",
    "    test_dir = '/kaggle/input/rsna-2024-lumbar-spine-mri/test_images'\n",
    "    test_csv = '/kaggle/input/rsna-2024-lumbar-spine-mri/test.csv'\n",
    "    test_series = '/kaggle/input/rsna-2024-lumbar-spine-mri/test_series_descriptions.csv'\n",
    "    # Note: competition paths seem to be 'rsna-knee-abnormality-detection' based on your previous logs. I will fix the path here.\n",
    "    base_dir = '/kaggle/input/competitions/rsna-knee-abnormality-detection'\n",
    "    test_csv = f'{base_dir}/test.csv'\n",
    "    test_series = f'{base_dir}/test_series.csv'\n",
    "    test_img_dir = f'{base_dir}/test_series'\n",
    "    \n",
    "    # Weights Path (You need to upload your 5 .pth files as a private Kaggle dataset and link it here)\n",
    "    weights_dir = '/kaggle/input/my-rsna-dino-weights'\n",
    "    \n",
    "    model_name = 'vit_base_patch14_reg4_dinov2.lvd142m'\n",
    "    img_size = 336\n",
    "    batch_size = 8\n",
    "    num_workers = 2\n",
    "    \n",
    "    crop_size_mm = 130.0\n",
    "    \n",
    "    conditions = [\n",
    "        'Spinal Canal Stenosis',\n",
    "        'Left Neural Foraminal Narrowing',\n",
    "        'Right Neural Foraminal Narrowing',\n",
    "        'Left Subarticular Stenosis',\n",
    "        'Right Subarticular Stenosis'\n",
    "    ] # Placeholder - need to map the 12 actual knee conditions\n",
    "    \n",
    "    # Update conditions to knee competition conditions\n",
    "    # Assuming standard RSNA format, we will extract condition names dynamically from sample_submission.csv\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "model_def",
   "metadata": {},
   "outputs": [],
   "source": [
    "class RSNAKneeModel(nn.Module):\n",
    "    def __init__(self, model_name, num_classes):\n",
    "        super().__init__()\n",
    "        self.backbone = timm.create_model(\n",
    "            model_name, \n",
    "            pretrained=False, \n",
    "            num_classes=0,\n",
    "            dynamic_img_size=True\n",
    "        )\n",
    "        self.head = nn.Sequential(\n",
    "            nn.Linear(self.backbone.num_features, 512),\n",
    "            nn.BatchNorm1d(512),\n",
    "            nn.SiLU(),\n",
    "            nn.Dropout(0.2),\n",
    "            nn.Linear(512, num_classes)\n",
    "        )\n",
    "        \n",
    "    def forward(self, x):\n",
    "        b, c, h, w = x.shape\n",
    "        features = self.backbone(x)\n",
    "        logits = self.head(features)\n",
    "        return logits"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "dicom_engine",
   "metadata": {},
   "outputs": [],
   "source": [
    "def extract_physical_geometry(dcm):\n",
    "    try:\n",
    "        pos = np.array([float(i) for i in dcm.ImagePositionPatient])\n",
    "        ori = np.array([float(i) for i in dcm.ImageOrientationPatient])\n",
    "        spacing = np.array([float(i) for i in dcm.PixelSpacing])\n",
    "    except:\n",
    "        return None, None, None, None\n",
    "    \n",
    "    row_cosines = ori[0:3]\n",
    "    col_cosines = ori[3:6]\n",
    "    normal = np.cross(row_cosines, col_cosines)\n",
    "    slice_position = np.dot(pos, normal)\n",
    "    return pos, spacing, normal, slice_position\n",
    "\n",
    "def load_dicom_volume(study_dir):\n",
    "    slices = []\n",
    "    for f in os.listdir(study_dir):\n",
    "        if f.endswith('.dcm'):\n",
    "            filepath = os.path.join(study_dir, f)\n",
    "            try:\n",
    "                dcm = pydicom.dcmread(filepath, stop_before_pixels=True)\n",
    "                _, spacing, _, z_pos = extract_physical_geometry(dcm)\n",
    "                if z_pos is not None:\n",
    "                    slices.append({\n",
    "                        'filepath': filepath,\n",
    "                        'z': z_pos,\n",
    "                        'spacing': spacing\n",
    "                    })\n",
    "            except:\n",
    "                continue\n",
    "                \n",
    "    if not slices:\n",
    "        return None\n",
    "        \n",
    "    # Sort anatomically by physical Z position\n",
    "    slices.sort(key=lambda x: x['z'])\n",
    "    \n",
    "    # Pick center 3 slices\n",
    "    n = len(slices)\n",
    "    if n >= 3:\n",
    "        mid = n // 2\n",
    "        chosen = [slices[mid-1], slices[mid], slices[mid+1]]\n",
    "    elif n == 2:\n",
    "        chosen = [slices[0], slices[0], slices[1]]\n",
    "    else:\n",
    "        chosen = [slices[0], slices[0], slices[0]]\n",
    "        \n",
    "    # Read pixels\n",
    "    volume = []\n",
    "    for s in chosen:\n",
    "        dcm = pydicom.dcmread(s['filepath'])\n",
    "        img = dcm.pixel_array\n",
    "        img = apply_voi_lut(img, dcm)\n",
    "        if dcm.PhotometricInterpretation == \"MONOCHROME1\":\n",
    "            img = np.max(img) - img\n",
    "        img = img - np.min(img)\n",
    "        img = img / (np.max(img) + 1e-6)\n",
    "        img = (img * 255).astype(np.uint8)\n",
    "        \n",
    "        # Center Crop using physical mm\n",
    "        h, w = img.shape\n",
    "        py, px = s['spacing']\n",
    "        crop_h = int(CFG.crop_size_mm / py)\n",
    "        crop_w = int(CFG.crop_size_mm / px)\n",
    "        \n",
    "        cy, cx = h//2, w//2\n",
    "        y1 = max(0, cy - crop_h//2)\n",
    "        y2 = min(h, cy + crop_h//2)\n",
    "        x1 = max(0, cx - crop_w//2)\n",
    "        x2 = min(w, cx + crop_w//2)\n",
    "        \n",
    "        img_cropped = img[y1:y2, x1:x2]\n",
    "        img_resized = cv2.resize(img_cropped, (CFG.img_size, CFG.img_size))\n",
    "        volume.append(img_resized)\n",
    "        \n",
    "    return np.stack(volume, axis=-1) # Shape: (H, W, 3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "dataset",
   "metadata": {},
   "outputs": [],
   "source": [
    "class RSNATestDataset(Dataset):\n",
    "    def __init__(self, df):\n",
    "        self.df = df\n",
    "        self.transforms = A.Compose([\n",
    "            A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),\n",
    "            ToTensorV2()\n",
    "        ])\n",
    "        \n",
    "    def __len__(self):\n",
    "        return len(self.df)\n",
    "        \n",
    "    def __getitem__(self, idx):\n",
    "        row = self.df.iloc[idx]\n",
    "        study_id = row['study_id']\n",
    "        study_dir = os.path.join(CFG.test_img_dir, str(study_id))\n",
    "        \n",
    "        img_volume = load_dicom_volume(study_dir)\n",
    "        if img_volume is None:\n",
    "            img_volume = np.zeros((CFG.img_size, CFG.img_size, 3), dtype=np.uint8)\n",
    "            \n",
    "        transformed = self.transforms(image=img_volume)\n",
    "        return transformed['image'], str(row['row_id']) if 'row_id' in row else str(study_id)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "inference_loop",
   "metadata": {},
   "outputs": [],
   "source": [
    "def run_inference():\n",
    "    # 1. Read Test Data\n",
    "    try:\n",
    "        test_df = pd.read_csv(CFG.test_csv)\n",
    "        sample_sub = pd.read_csv(f'{CFG.base_dir}/sample_submission.csv')\n",
    "        target_cols = [c for c in sample_sub.columns if c != 'row_id']\n",
    "        num_classes = len(target_cols)\n",
    "    except Exception as e:\n",
    "        print(f\"Could not load test data. Running on dummy data for save... {e}\")\n",
    "        # Dummy fallback so notebook saves cleanly\n",
    "        test_df = pd.DataFrame({'study_id': ['12345'], 'row_id': ['12345']})\n",
    "        target_cols = [f'target_{i}' for i in range(12)]\n",
    "        num_classes = 12\n",
    "\n",
    "    dataset = RSNATestDataset(test_df)\n",
    "    dataloader = DataLoader(dataset, batch_size=CFG.batch_size, shuffle=False, num_workers=CFG.num_workers)\n",
    "    \n",
    "    # 2. Load Models\n",
    "    models = []\n",
    "    model_paths = glob.glob(f\"{CFG.weights_dir}/*.pth\")\n",
    "    if not model_paths:\n",
    "        print(\"⚠️ Warning: No .pth models found in weights directory! Will output dummy predictions.\")\n",
    "    \n",
    "    for pth in model_paths:\n",
    "        print(f\"Loading model: {pth}\")\n",
    "        model = RSNAKneeModel(CFG.model_name, num_classes=num_classes)\n",
    "        model.load_state_dict(torch.load(pth, map_location=device))\n",
    "        model.to(device)\n",
    "        model.eval()\n",
    "        models.append(model)\n",
    "        \n",
    "    # 3. Predict\n",
    "    all_row_ids = []\n",
    "    all_preds = []\n",
    "    \n",
    "    with torch.no_grad():\n",
    "        for images, row_ids in dataloader:\n",
    "            images = images.to(device)\n",
    "            \n",
    "            # Ensemble averaging\n",
    "            batch_preds = torch.zeros((images.shape[0], num_classes)).to(device)\n",
    "            if models:\n",
    "                for model in models:\n",
    "                    logits = model(images)\n",
    "                    batch_preds += torch.sigmoid(logits)\n",
    "                batch_preds /= len(models)\n",
    "            \n",
    "            all_row_ids.extend(row_ids)\n",
    "            all_preds.append(batch_preds.cpu().numpy())\n",
    "            \n",
    "    if all_preds:\n",
    "        all_preds = np.vstack(all_preds)\n",
    "    else:\n",
    "        all_preds = np.zeros((len(test_df), num_classes))\n",
    "        \n",
    "    # 4. Save Submission\n",
    "    sub_df = pd.DataFrame(all_preds, columns=target_cols)\n",
    "    sub_df['row_id'] = all_row_ids\n",
    "    \n",
    "    # Reorder columns to match sample_submission\n",
    "    cols = ['row_id'] + target_cols\n",
    "    sub_df = sub_df[cols]\n",
    "    \n",
    "    sub_df.to_csv('submission.csv', index=False)\n",
    "    print(\"Saved submission.csv!\")\n",
    "    return sub_df\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    submission = run_inference()\n",
    "    display(submission.head())"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 }
}

with open('notebooks/RSNA_Knee_DINOv2_Inference.ipynb', 'w') as f:
    json.dump(notebook, f, indent=1)
print("Inference Notebook successfully generated!")
