import json
import os

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "id": "intro",
   "metadata": {},
   "source": [
    "# RSNA Knee Abnormality Detection: DINOv2 5-Fold Ensemble Inference\n",
    "- **Backbone:** DINOv2 Small (`vit_small_patch14_reg4_dinov2.lvd142m`)\n",
    "- **Preprocessing:** Physical Spacing Geometry Cropping (130mm FOV, 336px)\n",
    "- **Ensemble:** 5-Fold Averaging\n",
    "- **Rule:** Internet OFF"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "imports",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import gc\n",
    "import glob\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import cv2\n",
    "import pydicom\n",
    "from pydicom.pixel_data_handlers.util import apply_voi_lut\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "import timm\n",
    "import albumentations as A\n",
    "from tqdm.auto import tqdm\n",
    "\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print(f\"Using device: {device}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "config",
   "metadata": {},
   "outputs": [],
   "source": [
    "class CFG:\n",
    "    base_dir = '/kaggle/input/competitions/rsna-knee-abnormality-detection'\n",
    "    if not os.path.exists(base_dir):\n",
    "        base_dir = '/kaggle/input/rsna-knee-abnormality-detection'\n",
    "        \n",
    "    test_csv = os.path.join(base_dir, 'test.csv')\n",
    "    test_series_csv = os.path.join(base_dir, 'test_series.csv')\n",
    "    sample_sub_csv = os.path.join(base_dir, 'sample_submission.csv')\n",
    "    \n",
    "    # Check all possible image directory locations\n",
    "    test_series_dir = os.path.join(base_dir, 'test_series')\n",
    "    if not os.path.exists(test_series_dir):\n",
    "        test_series_dir = os.path.join(base_dir, 'test_images')\n",
    "    \n",
    "    # Weights directory from private dataset\n",
    "    weights_dir = '/kaggle/input/datasets/ahmedh4am/my-rsna-dino-weights'\n",
    "    if not os.path.exists(weights_dir):\n",
    "        weights_dir = '/kaggle/input/my-rsna-dino-weights'\n",
    "        \n",
    "    model_name = 'vit_small_patch14_reg4_dinov2.lvd142m'\n",
    "    image_size = 336\n",
    "    crop_mm = 130.0\n",
    "    batch_size = 8\n",
    "    num_workers = 2\n",
    "    \n",
    "    target_cols = [\n",
    "        'ACL', 'MCL', 'Medial Meniscus', 'Lateral Meniscus',\n",
    "        'Medial OA', 'Lateral OA', 'PF OA', 'Effusion',\n",
    "        'Synovitis', \"Baker's\", 'Contusion', 'Fracture'\n",
    "    ]\n",
    "\n",
    "print(f\"Base Dir: {CFG.base_dir}\")\n",
    "print(f\"Test Series Dir: {CFG.test_series_dir} (exists: {os.path.exists(CFG.test_series_dir)})\")\n",
    "print(f\"Weights Dir: {CFG.weights_dir} (exists: {os.path.exists(CFG.weights_dir)})\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "dicom_engine",
   "metadata": {},
   "outputs": [],
   "source": [
    "def extract_geometry(dcm):\n",
    "    try:\n",
    "        pos = np.array([float(i) for i in dcm.ImagePositionPatient])\n",
    "        ori = np.array([float(i) for i in dcm.ImageOrientationPatient])\n",
    "        spacing = np.array([float(i) for i in dcm.PixelSpacing])\n",
    "        normal = np.cross(ori[0:3], ori[3:6])\n",
    "        z_pos = np.dot(pos, normal)\n",
    "        return z_pos, spacing\n",
    "    except:\n",
    "        return None, None\n",
    "\n",
    "def sort_dicom_files(file_paths):\n",
    "    valid_files = []\n",
    "    for f in file_paths:\n",
    "        try:\n",
    "            dcm = pydicom.dcmread(f, stop_before_pixels=True)\n",
    "            z_pos, _ = extract_geometry(dcm)\n",
    "            if z_pos is not None:\n",
    "                valid_files.append((z_pos, getattr(dcm, 'InstanceNumber', 0), f))\n",
    "            else:\n",
    "                valid_files.append((0.0, getattr(dcm, 'InstanceNumber', 0), f))\n",
    "        except:\n",
    "            continue\n",
    "    valid_files.sort(key=lambda x: (x[0], x[1], x[2]))\n",
    "    return [f[2] for f in valid_files]\n",
    "\n",
    "def read_and_crop_dicom(filepath, crop_mm, target_size):\n",
    "    try:\n",
    "        dcm = pydicom.dcmread(filepath)\n",
    "        img = apply_voi_lut(dcm.pixel_array, dcm)\n",
    "        if dcm.PhotometricInterpretation == 'MONOCHROME1':\n",
    "            img = np.amax(img) - img\n",
    "        img = img - np.min(img)\n",
    "        img = img / (np.max(img) + 1e-6)\n",
    "        img = (img * 255).astype(np.uint8)\n",
    "        \n",
    "        spacing_y, spacing_x = 1.0, 1.0\n",
    "        if hasattr(dcm, 'PixelSpacing'):\n",
    "            try:\n",
    "                spacing_y, spacing_x = [float(s) for s in dcm.PixelSpacing]\n",
    "            except:\n",
    "                pass\n",
    "        \n",
    "        h, w = img.shape\n",
    "        crop_h = min(int(crop_mm / spacing_y), h)\n",
    "        crop_w = min(int(crop_mm / spacing_x), w)\n",
    "        start_y = (h - crop_h) // 2\n",
    "        start_x = (w - crop_w) // 2\n",
    "        \n",
    "        cropped_img = img[start_y:start_y+crop_h, start_x:start_x+crop_w]\n",
    "        return cv2.resize(cropped_img, (target_size, target_size), interpolation=cv2.INTER_CUBIC)\n",
    "    except:\n",
    "        return np.zeros((target_size, target_size), dtype=np.uint8)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "dataset",
   "metadata": {},
   "outputs": [],
   "source": [
    "class RSNAKneeInferenceDataset(Dataset):\n",
    "    def __init__(self, df, series_df):\n",
    "        self.df = df.reset_index(drop=True)\n",
    "        self.series_df = series_df\n",
    "        self.transform = A.Compose([\n",
    "            A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225))\n",
    "        ])\n",
    "\n",
    "    def __len__(self):\n",
    "        return len(self.df)\n",
    "\n",
    "    def _find_series_dir(self, study_id):\n",
    "        # Check matched series from test_series.csv\n",
    "        study_matches = self.series_df[self.series_df['StudyInstanceUID'] == study_id]\n",
    "        \n",
    "        # Try primary match from CSV\n",
    "        if len(study_matches) > 0:\n",
    "            for _, row in study_matches.iterrows():\n",
    "                s_id = str(row['SeriesInstanceUID'])\n",
    "                direct_path = os.path.join(CFG.test_series_dir, str(study_id), s_id)\n",
    "                if os.path.exists(direct_path):\n",
    "                    return direct_path\n",
    "        \n",
    "        # Fallback: scan filesystem directly if CSV path differs\n",
    "        study_folder = os.path.join(CFG.test_series_dir, str(study_id))\n",
    "        if os.path.exists(study_folder):\n",
    "            subfolders = [os.path.join(study_folder, s) for s in os.listdir(study_folder) if os.path.isdir(os.path.join(study_folder, s))]\n",
    "            if subfolders:\n",
    "                return subfolders[0]\n",
    "            return study_folder\n",
    "        return None\n",
    "\n",
    "    def __getitem__(self, idx):\n",
    "        row = self.df.iloc[idx]\n",
    "        study_id = str(row['StudyInstanceUID'])\n",
    "        series_dir = self._find_series_dir(study_id)\n",
    "        \n",
    "        sorted_files = []\n",
    "        if series_dir and os.path.exists(series_dir):\n",
    "            dcm_files = [os.path.join(series_dir, f) for f in os.listdir(series_dir) if f.endswith('.dcm')]\n",
    "            if dcm_files:\n",
    "                sorted_files = sort_dicom_files(dcm_files)\n",
    "        \n",
    "        num_triplets = 3\n",
    "        images = []\n",
    "        if len(sorted_files) >= 3:\n",
    "            valid_files = sorted_files[int(len(sorted_files)*0.2):int(len(sorted_files)*0.8)]\n",
    "            if len(valid_files) < 3:\n",
    "                valid_files = sorted_files\n",
    "            anchors = np.linspace(0, len(valid_files)-1, num_triplets, dtype=int)\n",
    "            \n",
    "            for anchor in anchors:\n",
    "                img_R = read_and_crop_dicom(valid_files[max(0, anchor-1)], CFG.crop_mm, CFG.image_size)\n",
    "                img_G = read_and_crop_dicom(valid_files[anchor], CFG.crop_mm, CFG.image_size)\n",
    "                img_B = read_and_crop_dicom(valid_files[min(len(valid_files)-1, anchor+1)], CFG.crop_mm, CFG.image_size)\n",
    "                \n",
    "                rgb_img = self.transform(image=np.stack([img_R, img_G, img_B], axis=-1))['image']\n",
    "                images.append(torch.tensor(rgb_img, dtype=torch.float32).permute(2, 0, 1))\n",
    "        elif len(sorted_files) > 0:\n",
    "            # Less than 3 slices: replicate available slice\n",
    "            img = read_and_crop_dicom(sorted_files[0], CFG.crop_mm, CFG.image_size)\n",
    "            rgb_img = self.transform(image=np.stack([img, img, img], axis=-1))['image']\n",
    "            tensor_img = torch.tensor(rgb_img, dtype=torch.float32).permute(2, 0, 1)\n",
    "            for _ in range(num_triplets):\n",
    "                images.append(tensor_img)\n",
    "                \n",
    "        while len(images) < num_triplets:\n",
    "            images.append(torch.zeros((3, CFG.image_size, CFG.image_size)))\n",
    "        \n",
    "        images_tensor = torch.stack(images)\n",
    "        return images_tensor, study_id\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "model",
   "metadata": {},
   "outputs": [],
   "source": [
    "class DINOv2KneeModel(nn.Module):\n",
    "    def __init__(self, model_name=CFG.model_name, num_classes=12):\n",
    "        super().__init__()\n",
    "        self.encoder = timm.create_model(model_name, pretrained=False, num_classes=0, dynamic_img_size=True)\n",
    "        self.head = nn.Sequential(nn.Dropout(0.2), nn.Linear(self.encoder.num_features, num_classes))\n",
    "\n",
    "    def forward(self, x):\n",
    "        batch_size, num_triplets, c, h, w = x.shape\n",
    "        features = self.encoder(x.view(-1, c, h, w))\n",
    "        logits, _ = torch.max(self.head(features).view(batch_size, num_triplets, -1), dim=1)\n",
    "        return logits\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "inference",
   "metadata": {},
   "outputs": [],
   "source": [
    "def run_inference():\n",
    "    num_classes = len(CFG.target_cols)\n",
    "    \n",
    "    # 1. Load Data\n",
    "    if os.path.exists(CFG.sample_sub_csv):\n",
    "        sample_sub = pd.read_csv(CFG.sample_sub_csv)\n",
    "        print(f\"Loaded sample_submission.csv: {sample_sub.shape}\")\n",
    "    else:\n",
    "        sample_sub = pd.DataFrame({\n",
    "            'StudyInstanceUID': ['dummy_1', 'dummy_2']\n",
    "        })\n",
    "        for col in CFG.target_cols:\n",
    "            sample_sub[col] = 0.5\n",
    "            \n",
    "    if os.path.exists(CFG.test_csv):\n",
    "        test_df = pd.read_csv(CFG.test_csv)\n",
    "    else:\n",
    "        test_df = sample_sub[['StudyInstanceUID']].copy()\n",
    "        \n",
    "    if os.path.exists(CFG.test_series_csv):\n",
    "        test_series_df = pd.read_csv(CFG.test_series_csv)\n",
    "    else:\n",
    "        test_series_df = pd.DataFrame(columns=['StudyInstanceUID', 'SeriesInstanceUID'])\n",
    "        \n",
    "    dataset = RSNAKneeInferenceDataset(test_df, test_series_df)\n",
    "    dataloader = DataLoader(\n",
    "        dataset, \n",
    "        batch_size=CFG.batch_size, \n",
    "        shuffle=False, \n",
    "        num_workers=CFG.num_workers,\n",
    "        pin_memory=True\n",
    "    )\n",
    "    \n",
    "    # 2. Load 5-Fold Models\n",
    "    models = []\n",
    "    model_paths = sorted(glob.glob(os.path.join(CFG.weights_dir, \"*.pth\")))\n",
    "    print(f\"Found {len(model_paths)} model weights:\")\n",
    "    for pth in model_paths:\n",
    "        print(f\"  --> Loading {os.path.basename(pth)}\")\n",
    "        model = DINOv2KneeModel(num_classes=num_classes)\n",
    "        model.load_state_dict(torch.load(pth, map_location=device))\n",
    "        model.to(device)\n",
    "        model.eval()\n",
    "        models.append(model)\n",
    "        \n",
    "    if not models:\n",
    "        print(\"⚠️ No .pth weights found! Initializing single model fallback.\")\n",
    "        model = DINOv2KneeModel(num_classes=num_classes).to(device)\n",
    "        model.eval()\n",
    "        models.append(model)\n",
    "        \n",
    "    # 3. Predict\n",
    "    all_study_ids = []\n",
    "    all_preds = []\n",
    "    \n",
    "    with torch.no_grad():\n",
    "        for images, study_ids in tqdm(dataloader, desc=\"Inference\"):\n",
    "            images = images.to(device)\n",
    "            batch_preds = torch.zeros((images.shape[0], num_classes), device=device)\n",
    "            \n",
    "            for model in models:\n",
    "                batch_preds += torch.sigmoid(model(images))\n",
    "            batch_preds /= len(models)\n",
    "            \n",
    "            all_study_ids.extend(study_ids)\n",
    "            all_preds.append(batch_preds.cpu().numpy())\n",
    "            \n",
    "    all_preds = np.vstack(all_preds)\n",
    "    pred_df = pd.DataFrame(all_preds, columns=CFG.target_cols)\n",
    "    pred_df['StudyInstanceUID'] = all_study_ids\n",
    "    \n",
    "    # 4. Strictly Align with sample_submission.csv format\n",
    "    submission_df = sample_sub[['StudyInstanceUID']].merge(pred_df, on='StudyInstanceUID', how='left')\n",
    "    submission_df = submission_df.fillna(0.5)\n",
    "    \n",
    "    # Enforce exact column order from sample_sub\n",
    "    final_cols = ['StudyInstanceUID'] + [c for c in CFG.target_cols if c in sample_sub.columns or c != 'StudyInstanceUID']\n",
    "    submission_df = submission_df[final_cols]\n",
    "    \n",
    "    submission_df.to_csv('submission.csv', index=False)\n",
    "    print(f\"\\nSubmission generated successfully: {submission_df.shape}\")\n",
    "    return submission_df\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    sub = run_inference()\n",
    "    display(sub.head(10))\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

os.makedirs('notebooks', exist_ok=True)
with open('notebooks/RSNA_Knee_DINOv2_Inference.ipynb', 'w') as f:
    json.dump(notebook, f, indent=2)

print("Inference notebook successfully rebuilt and validated.")
