import json
import os

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "id": "intro",
   "metadata": {},
   "source": [
    "# RSNA Knee Abnormality Detection: DINOv2 Inference\n",
    "**⚠️ IMPORTANT:** You must turn **Internet OFF** in the Kaggle right-side panel for this submission to work!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "imports",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import gc\n",
    "import glob\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import cv2\n",
    "import pydicom\n",
    "from pydicom.pixel_data_handlers.util import apply_voi_lut\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "import timm\n",
    "import albumentations as A\n",
    "from tqdm.auto import tqdm\n",
    "\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print(f\"Using device: {device}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "config",
   "metadata": {},
   "outputs": [],
   "source": [
    "class CFG:\n",
    "    base_dir = '/kaggle/input/competitions/rsna-knee-abnormality-detection'\n",
    "    test_csv = f'{base_dir}/test.csv'\n",
    "    test_series = f'{base_dir}/test_series.csv'\n",
    "    test_images_dir = f'{base_dir}/test_images'\n",
    "    \n",
    "    weights_dir = '/kaggle/input/datasets/ahmedh4am/my-rsna-dino-weights'\n",
    "    model_name = 'vit_small_patch14_reg4_dinov2.lvd142m'\n",
    "    \n",
    "    image_size = 336\n",
    "    crop_mm = 130.0\n",
    "    batch_size = 8\n",
    "    num_workers = 2\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "dicom_logic",
   "metadata": {},
   "outputs": [],
   "source": [
    "def extract_geometry(dcm):\n",
    "    try:\n",
    "        pos = np.array([float(i) for i in dcm.ImagePositionPatient])\n",
    "        ori = np.array([float(i) for i in dcm.ImageOrientationPatient])\n",
    "        spacing = np.array([float(i) for i in dcm.PixelSpacing])\n",
    "        normal = np.cross(ori[0:3], ori[3:6])\n",
    "        z_pos = np.dot(pos, normal)\n",
    "        return z_pos, spacing\n",
    "    except:\n",
    "        return None, None\n",
    "\n",
    "def sort_dicom_files(file_paths):\n",
    "    valid_files = []\n",
    "    for f in file_paths:\n",
    "        try:\n",
    "            dcm = pydicom.dcmread(f, stop_before_pixels=True)\n",
    "            z_pos, _ = extract_geometry(dcm)\n",
    "            if z_pos is not None: valid_files.append((z_pos, f))\n",
    "        except:\n",
    "            pass\n",
    "    valid_files.sort(key=lambda x: x[0])\n",
    "    return [f[1] for f in valid_files]\n",
    "\n",
    "def read_and_crop_dicom(filepath, crop_mm, target_size):\n",
    "    try:\n",
    "        dcm = pydicom.dcmread(filepath)\n",
    "        img = dcm.pixel_array\n",
    "        img = apply_voi_lut(img, dcm)\n",
    "        if dcm.PhotometricInterpretation == 'MONOCHROME1': img = np.max(img) - img\n",
    "        img = img - np.min(img)\n",
    "        img = img / (np.max(img) + 1e-6)\n",
    "        img = (img * 255).astype(np.uint8)\n",
    "        \n",
    "        _, spacing = extract_geometry(dcm)\n",
    "        if spacing is None: spacing = (0.5, 0.5)\n",
    "        \n",
    "        h, w = img.shape\n",
    "        crop_h, crop_w = int(crop_mm / spacing[0]), int(crop_mm / spacing[1])\n",
    "        cy, cx = h // 2, w // 2\n",
    "        y1, y2 = max(0, cy - crop_h // 2), min(h, cy + crop_h // 2)\n",
    "        x1, x2 = max(0, cx - crop_w // 2), min(w, cx + crop_w // 2)\n",
    "        \n",
    "        img = img[y1:y2, x1:x2]\n",
    "        img = cv2.resize(img, (target_size, target_size))\n",
    "        return img\n",
    "    except:\n",
    "        return np.zeros((target_size, target_size), dtype=np.uint8)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "dataset",
   "metadata": {},
   "outputs": [],
   "source": [
    "class RSNAKneeInferenceDataset(Dataset):\n",
    "    def __init__(self, df, series_df):\n",
    "        self.df = df\n",
    "        self.series_df = series_df\n",
    "        self.transform = A.Compose([A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225))])\n",
    "\n",
    "    def __len__(self):\n",
    "        return len(self.df)\n",
    "\n",
    "    def __getitem__(self, idx):\n",
    "        row = self.df.iloc[idx]\n",
    "        study_id = row['study_id']\n",
    "        \n",
    "        study_series = self.series_df[self.series_df['study_id'] == study_id]\n",
    "        if len(study_series) > 0:\n",
    "            series_id = study_series.iloc[0]['series_id']\n",
    "            series_dir = os.path.join(CFG.test_images_dir, str(study_id), str(series_id))\n",
    "        else:\n",
    "            series_dir = \"none\"\n",
    "            \n",
    "        sorted_files = []\n",
    "        if os.path.exists(series_dir):\n",
    "            sorted_files = sort_dicom_files([os.path.join(series_dir, f) for f in os.listdir(series_dir) if f.endswith('.dcm')])\n",
    "        \n",
    "        num_triplets = 3\n",
    "        images = []\n",
    "        if len(sorted_files) >= 3:\n",
    "            valid_files = sorted_files[int(len(sorted_files)*0.2):int(len(sorted_files)*0.8)]\n",
    "            if len(valid_files) < 3: valid_files = sorted_files\n",
    "            anchors = np.linspace(0, len(valid_files)-1, num_triplets, dtype=int)\n",
    "            \n",
    "            for anchor in anchors:\n",
    "                img_R = read_and_crop_dicom(valid_files[max(0, anchor-1)], CFG.crop_mm, CFG.image_size)\n",
    "                img_G = read_and_crop_dicom(valid_files[anchor], CFG.crop_mm, CFG.image_size)\n",
    "                img_B = read_and_crop_dicom(valid_files[min(len(valid_files)-1, anchor+1)], CFG.crop_mm, CFG.image_size)\n",
    "                \n",
    "                rgb_img = self.transform(image=np.stack([img_R, img_G, img_B], axis=-1))['image']\n",
    "                images.append(torch.tensor(rgb_img, dtype=torch.float32).permute(2, 0, 1))\n",
    "                \n",
    "        while len(images) < num_triplets: images.append(torch.zeros((3, CFG.image_size, CFG.image_size)))\n",
    "        \n",
    "        images_tensor = torch.stack(images)\n",
    "        return images_tensor, row['row_id'] if 'row_id' in row else str(study_id)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "model",
   "metadata": {},
   "outputs": [],
   "source": [
    "class DINOv2KneeModel(nn.Module):\n",
    "    def __init__(self, model_name=CFG.model_name, num_classes=12):\n",
    "        super().__init__()\n",
    "        self.encoder = timm.create_model(model_name, pretrained=False, num_classes=0, dynamic_img_size=True)\n",
    "        self.head = nn.Sequential(nn.Dropout(0.2), nn.Linear(self.encoder.num_features, num_classes))\n",
    "\n",
    "    def forward(self, x):\n",
    "        batch_size, num_triplets, c, h, w = x.shape\n",
    "        features = self.encoder(x.view(-1, c, h, w))\n",
    "        logits, _ = torch.max(self.head(features).view(batch_size, num_triplets, -1), dim=1) \n",
    "        return logits\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "inference",
   "metadata": {},
   "outputs": [],
   "source": [
    "def run_inference():\n",
    "    try:\n",
    "        test_df = pd.read_csv(CFG.test_csv)\n",
    "        test_series_df = pd.read_csv(CFG.test_series)\n",
    "        sample_sub = pd.read_csv(f'{CFG.base_dir}/sample_submission.csv')\n",
    "        target_cols = [c for c in sample_sub.columns if c != 'row_id']\n",
    "        num_classes = len(target_cols)\n",
    "    except:\n",
    "        print(\"Running in fallback mode for notebook save\")\n",
    "        test_df = pd.DataFrame({'study_id': ['123'], 'row_id': ['123']})\n",
    "        test_series_df = pd.DataFrame({'study_id': ['123'], 'series_id': ['456']})\n",
    "        target_cols = [f'target_{i}' for i in range(12)]\n",
    "        num_classes = 12\n",
    "\n",
    "    dataset = RSNAKneeInferenceDataset(test_df, test_series_df)\n",
    "    dataloader = DataLoader(dataset, batch_size=CFG.batch_size, shuffle=False, num_workers=CFG.num_workers)\n",
    "    \n",
    "    models = []\n",
    "    model_paths = glob.glob(f\"{CFG.weights_dir}/*.pth\")\n",
    "    for pth in model_paths:\n",
    "        print(f\"Loading {pth}\")\n",
    "        model = DINOv2KneeModel(num_classes=num_classes)\n",
    "        model.load_state_dict(torch.load(pth, map_location=device))\n",
    "        model.to(device)\n",
    "        model.eval()\n",
    "        models.append(model)\n",
    "        \n",
    "    all_row_ids, all_preds = [], []\n",
    "    with torch.no_grad():\n",
    "        for images, row_ids in tqdm(dataloader):\n",
    "            images = images.to(device)\n",
    "            batch_preds = torch.zeros((images.shape[0], num_classes)).to(device)\n",
    "            if models:\n",
    "                for model in models:\n",
    "                    batch_preds += torch.sigmoid(model(images))\n",
    "                batch_preds /= len(models)\n",
    "            all_row_ids.extend(row_ids)\n",
    "            all_preds.append(batch_preds.cpu().numpy())\n",
    "            \n",
    "    all_preds = np.vstack(all_preds) if all_preds else np.zeros((len(test_df), num_classes))\n",
    "    sub_df = pd.DataFrame(all_preds, columns=target_cols)\n",
    "    sub_df['row_id'] = all_row_ids\n",
    "    sub_df = sub_df[['row_id'] + target_cols]\n",
    "    sub_df.to_csv('submission.csv', index=False)\n",
    "    return sub_df\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    sub = run_inference()\n",
    "    display(sub.head())\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

os.makedirs('notebooks', exist_ok=True)
with open('notebooks/RSNA_Knee_DINOv2_Inference.ipynb', 'w') as f:
    json.dump(notebook, f, indent=2)

print("Fixed Inference Notebook successfully generated!")
