import json
import os

cells = [
    {
        'cell_type': 'markdown',
        'metadata': {},
        'source': [
            '# RSNA Knee Abnormality Detection\n',
            '## Multi-Planar DINOv2 5-Fold Ensemble Inference Pipeline\n',
            '---\n',
            '**Key Features:**\n',
            '- **Multi-Planar Fusion**: Evaluates Sagittal, Coronal, and Axial planes simultaneously.\n',
            '- **5-Fold Cross-View Ensemble**: Combines predictions from all 5 trained fold checkpoints.\n',
            '- **Test-Time Augmentation (TTA)**: Multi-pass inference for maximum calibration.\n',
            '- **Offline Compliant**: Runs with **Internet OFF** on Kaggle.'
        ]
    },
    {
        'cell_type': 'code',
        'metadata': {},
        'outputs': [],
        'execution_count': None,
        'source': [
            '# CELL 1: Imports & Offline Setup\n',
            'import os\n',
            'import gc\n',
            'import glob\n',
            'import numpy as np\n',
            'import pandas as pd\n',
            'import cv2\n',
            'import pydicom\n',
            'from pydicom.pixel_data_handlers.util import apply_voi_lut\n',
            'from tqdm.auto import tqdm\n',
            '\n',
            'import torch\n',
            'import torch.nn as nn\n',
            'from torch.utils.data import Dataset, DataLoader\n',
            'import timm\n',
            'import albumentations as A\n',
            'from albumentations.pytorch import ToTensorV2\n',
            '\n',
            'device = torch.device("cuda" if torch.cuda.is_available() else "cpu")\n',
            'print(f"Inference Device: {device} | PyTorch: {torch.__version__}")\n'
        ]
    },
    {
        'cell_type': 'code',
        'metadata': {},
        'outputs': [],
        'execution_count': None,
        'source': [
            '# CELL 2: Configuration & Path Resolution Engine\n',
            'class CFG:\n',
            '    base_dir = "/kaggle/input/competitions/rsna-knee-abnormality-detection"\n',
            '    if not os.path.exists(base_dir):\n',
            '        base_dir = "/kaggle/input/rsna-knee-abnormality-detection"\n',
            '        \n',
            '    test_csv = os.path.join(base_dir, "test.csv")\n',
            '    test_series_csv = os.path.join(base_dir, "test_series.csv")\n',
            '    sample_sub_csv = os.path.join(base_dir, "sample_submission.csv")\n',
            '    \n',
            '    # Dynamic resolution for test DICOMs\n',
            '    test_series_dir = os.path.join(base_dir, "test_series")\n',
            '    if not os.path.exists(test_series_dir):\n',
            '        test_series_dir = os.path.join(base_dir, "test_images")\n',
            '        \n',
            '    # Weights directory where 5-fold .pth files are mounted\n',
            '    weights_dir = "/kaggle/input/datasets/ahmedh4am/my-rsna-dino-weights"\n',
            '    if not os.path.exists(weights_dir):\n',
            '        weights_dir = "/kaggle/input/my-rsna-dino-weights"\n',
            '        \n',
            '    model_name = "vit_small_patch14_reg4_dinov2.lvd142m"\n',
            '    image_size = 336\n',
            '    crop_mm = 130.0\n',
            '    num_views = 3\n',
            '    batch_size = 8\n',
            '    num_workers = 2\n',
            '    use_tta = True\n',
            '    \n',
            '    target_cols = [\n',
            '        "ACL", "MCL", "Medial Meniscus", "Lateral Meniscus",\n',
            '        "Medial OA", "Lateral OA", "PF OA", "Effusion",\n',
            '        "Synovitis", "Baker\'s", "Contusion", "Fracture"\n',
            '    ]\n',
            '\n',
            'print(f"Base Directory: {CFG.base_dir}")\n',
            'print(f"Test Series Directory: {CFG.test_series_dir} (exists: {os.path.exists(CFG.test_series_dir)})")\n',
            'print(f"Weights Directory: {CFG.weights_dir} (exists: {os.path.exists(CFG.weights_dir)})")\n'
        ]
    },
    {
        'cell_type': 'code',
        'metadata': {},
        'outputs': [],
        'execution_count': None,
        'source': [
            '# CELL 3: Physical Geometry DICOM Processing\n',
            'def get_slice_position(dcm):\n',
            '    if hasattr(dcm, "ImageOrientationPatient") and hasattr(dcm, "ImagePositionPatient"):\n',
            '        try:\n',
            '            pos = np.array([float(x) for x in dcm.ImagePositionPatient])\n',
            '            ori = np.array([float(x) for x in dcm.ImageOrientationPatient])\n',
            '            normal = np.cross(ori[0:3], ori[3:6])\n',
            '            return np.dot(pos, normal)\n',
            '        except:\n',
            '            pass\n',
            '    if hasattr(dcm, "SliceLocation"): return float(dcm.SliceLocation)\n',
            '    if hasattr(dcm, "InstanceNumber"): return float(dcm.InstanceNumber)\n',
            '    return 0.0\n',
            '\n',
            'def sort_dicom_files(dicom_paths):\n',
            '    metadata = []\n',
            '    for path in dicom_paths:\n',
            '        try:\n',
            '            dcm = pydicom.dcmread(path, stop_before_pixels=True)\n',
            '            metadata.append({\n',
            '                "path": path,\n',
            '                "pos": get_slice_position(dcm),\n',
            '                "instance": getattr(dcm, "InstanceNumber", 0)\n',
            '            })\n',
            '        except:\n',
            '            continue\n',
            '    metadata.sort(key=lambda x: (x["pos"], x["instance"], x["path"]))\n',
            '    return [x["path"] for x in metadata]\n',
            '\n',
            'def read_and_crop_dicom(path, crop_mm=130.0, target_size=336):\n',
            '    try:\n',
            '        dcm = pydicom.dcmread(path)\n',
            '        img = apply_voi_lut(dcm.pixel_array, dcm)\n',
            '        if dcm.PhotometricInterpretation == "MONOCHROME1":\n',
            '            img = np.amax(img) - img\n',
            '        img = img - np.min(img)\n',
            '        img = img / (np.max(img) + 1e-6)\n',
            '        img = (img * 255).astype(np.uint8)\n',
            '        \n',
            '        spacing_y, spacing_x = 1.0, 1.0\n',
            '        if hasattr(dcm, "PixelSpacing"):\n',
            '            try: spacing_y, spacing_x = [float(s) for s in dcm.PixelSpacing]\n',
            '            except: pass\n',
            '        \n',
            '        h, w = img.shape\n',
            '        crop_h = min(int(crop_mm / spacing_y), h)\n',
            '        crop_w = min(int(crop_mm / spacing_x), w)\n',
            '        start_y = (h - crop_h) // 2\n',
            '        start_x = (w - crop_w) // 2\n',
            '        \n',
            '        cropped = img[start_y:start_y+crop_h, start_x:start_x+crop_w]\n',
            '        return cv2.resize(cropped, (target_size, target_size), interpolation=cv2.INTER_CUBIC)\n',
            '    except:\n',
            '        return np.zeros((target_size, target_size), dtype=np.uint8)\n',
            '\n',
            'def extract_plane_triplets(series_dir, crop_mm=130.0, target_size=336):\n',
            '    if not series_dir or not os.path.exists(series_dir):\n',
            '        return np.zeros((target_size, target_size, 3), dtype=np.uint8)\n',
            '        \n',
            '    dcm_files = [os.path.join(series_dir, f) for f in os.listdir(series_dir) if f.endswith(".dcm")]\n',
            '    if not dcm_files:\n',
            '        return np.zeros((target_size, target_size, 3), dtype=np.uint8)\n',
            '        \n',
            '    sorted_files = sort_dicom_files(dcm_files)\n',
            '    n = len(sorted_files)\n',
            '    if n >= 3:\n',
            '        mid = n // 2\n',
            '        f_r = sorted_files[mid - 1]\n',
            '        f_g = sorted_files[mid]\n',
            '        f_b = sorted_files[min(n - 1, mid + 1)]\n',
            '    elif n == 2:\n',
            '        f_r, f_g, f_b = sorted_files[0], sorted_files[1], sorted_files[1]\n',
            '    else:\n',
            '        f_r = f_g = f_b = sorted_files[0]\n',
            '        \n',
            '    img_r = read_and_crop_dicom(f_r, crop_mm, target_size)\n',
            '    img_g = read_and_crop_dicom(f_g, crop_mm, target_size)\n',
            '    img_b = read_and_crop_dicom(f_b, crop_mm, target_size)\n',
            '    \n',
            '    return np.stack([img_r, img_g, img_b], axis=-1)\n'
        ]
    },
    {
        'cell_type': 'code',
        'metadata': {},
        'outputs': [],
        'execution_count': None,
        'source': [
            '# CELL 4: Multi-Planar Inference Dataset\n',
            'inference_transforms = A.Compose([\n',
            '    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),\n',
            '    ToTensorV2()\n',
            '])\n',
            '\n',
            'class RSNAKneeMultiViewInferenceDataset(Dataset):\n',
            '    def __init__(self, df, series_df, images_base_dir):\n',
            '        self.df = df.reset_index(drop=True)\n',
            '        self.series_df = series_df\n',
            '        self.images_base_dir = images_base_dir\n',
            '        self.transform = inference_transforms\n',
            '        self.planes = ["Sagittal", "Coronal", "Axial"]\n',
            '\n',
            '    def __len__(self):\n',
            '        return len(self.df)\n',
            '\n',
            '    def _find_plane_dir(self, study_id, plane, study_series):\n',
            '        # 1. Match from series_df\n',
            '        plane_series = study_series[study_series["Anatomical_Plane"] == plane]\n',
            '        if len(plane_series) > 0:\n',
            '            fs_series = plane_series[plane_series["Fluid_Sensitive"] == 1]\n',
            '            if len(fs_series) > 0:\n',
            '                s_id = str(fs_series.iloc[0]["SeriesInstanceUID"])\n',
            '            else:\n',
            '                s_id = str(plane_series.iloc[0]["SeriesInstanceUID"])\n',
            '                \n',
            '            direct_path = os.path.join(self.images_base_dir, study_id, s_id)\n',
            '            if os.path.exists(direct_path):\n',
            '                return direct_path\n',
            '                \n',
            '        # 2. Dynamic Fallback: scan study subfolders\n',
            '        study_folder = os.path.join(self.images_base_dir, study_id)\n',
            '        if os.path.exists(study_folder):\n',
            '            subfolders = [os.path.join(study_folder, s) for s in os.listdir(study_folder) if os.path.isdir(os.path.join(study_folder, s))]\n',
            '            if subfolders:\n',
            '                return subfolders[0]\n',
            '            return study_folder\n',
            '        return None\n',
            '\n',
            '    def __getitem__(self, idx):\n',
            '        row = self.df.iloc[idx]\n',
            '        study_id = str(row["StudyInstanceUID"])\n',
            '        study_series = self.series_df[self.series_df["StudyInstanceUID"] == study_id]\n',
            '        \n',
            '        view_tensors = []\n',
            '        for plane in self.planes:\n',
            '            series_dir = self._find_plane_dir(study_id, plane, study_series)\n',
            '            rgb_img = extract_plane_triplets(series_dir, CFG.crop_mm, CFG.image_size)\n',
            '            transformed = self.transform(image=rgb_img)["image"] # (3, H, W)\n',
            '            view_tensors.append(transformed)\n',
            '            \n',
            '        # Stack views -> Shape: (3, 3, H, W)\n',
            '        stacked_views = torch.stack(view_tensors, dim=0)\n',
            '        return stacked_views, study_id\n'
        ]
    },
    {
        'cell_type': 'code',
        'metadata': {},
        'outputs': [],
        'execution_count': None,
        'source': [
            '# CELL 5: Multi-Planar Vision Transformer Model Definition\n',
            'class MultiViewDINOv2KneeModel(nn.Module):\n',
            '    def __init__(self, model_name=CFG.model_name, num_classes=12, num_views=3):\n',
            '        super().__init__()\n',
            '        self.num_views = num_views\n',
            '        self.encoder = timm.create_model(\n',
            '            model_name,\n',
            '            pretrained=False,\n',
            '            num_classes=0,\n',
            '            dynamic_img_size=True\n',
            '        )\n',
            '        embed_dim = self.encoder.num_features\n',
            '        \n',
            '        # Cross-View Gated Attention Pooling\n',
            '        self.view_gate = nn.Sequential(\n',
            '            nn.Linear(embed_dim, 128),\n',
            '            nn.Tanh(),\n',
            '            nn.Linear(128, 1)\n',
            '        )\n',
            '        \n',
            '        # Multi-Label Classifier Head\n',
            '        self.head = nn.Sequential(\n',
            '            nn.LayerNorm(embed_dim),\n',
            '            nn.Dropout(0.3),\n',
            '            nn.Linear(embed_dim, 256),\n',
            '            nn.GELU(),\n',
            '            nn.Dropout(0.2),\n',
            '            nn.Linear(256, num_classes)\n',
            '        )\n',
            '\n',
            '    def forward(self, x):\n',
            '        B, V, C, H, W = x.shape\n',
            '        x_flat = x.view(B * V, C, H, W)\n',
            '        features = self.encoder(x_flat)\n',
            '        features = features.view(B, V, -1)\n',
            '        \n',
            '        attn_scores = self.view_gate(features)\n',
            '        attn_weights = torch.softmax(attn_scores, dim=1)\n',
            '        pooled_features = torch.sum(features * attn_weights, dim=1)\n',
            '        logits = self.head(pooled_features)\n',
            '        return logits\n'
        ]
    },
    {
        'cell_type': 'code',
        'metadata': {},
        'outputs': [],
        'execution_count': None,
        'source': [
            '# CELL 6: 5-Fold Ensemble Inference & Submission\n',
            'def run_multiview_inference():\n',
            '    num_classes = len(CFG.target_cols)\n',
            '    \n',
            '    # 1. Load Ground Truth/Sample Submissions\n',
            '    if os.path.exists(CFG.sample_sub_csv):\n',
            '        sample_sub = pd.read_csv(CFG.sample_sub_csv)\n',
            '        print(f"Loaded sample_submission.csv: {sample_sub.shape}")\n',
            '    else:\n',
            '        sample_sub = pd.DataFrame({\n',
            '            "StudyInstanceUID": ["dummy_study_1", "dummy_study_2"]\n',
            '        })\n',
            '        for c in CFG.target_cols: sample_sub[c] = 0.5\n',
            '        \n',
            '    if os.path.exists(CFG.test_csv):\n',
            '        test_df = pd.read_csv(CFG.test_csv)\n',
            '    else:\n',
            '        test_df = sample_sub[["StudyInstanceUID"]].copy()\n',
            '        \n',
            '    if os.path.exists(CFG.test_series_csv):\n',
            '        test_series_df = pd.read_csv(CFG.test_series_csv)\n',
            '    else:\n',
            '        test_series_df = pd.DataFrame(columns=["StudyInstanceUID", "SeriesInstanceUID", "Anatomical_Plane", "Fluid_Sensitive"])\n',
            '        \n',
            '    print(f"Total test studies to predict: {len(test_df)}")\n',
            '    dataset = RSNAKneeMultiViewInferenceDataset(test_df, test_series_df, CFG.test_series_dir)\n',
            '    dataloader = DataLoader(dataset, batch_size=CFG.batch_size, shuffle=False, num_workers=CFG.num_workers, pin_memory=True)\n',
            '    \n',
            '    # 2. Load Trained 5-Fold Weights\n',
            '    models = []\n',
            '    model_paths = sorted(glob.glob(os.path.join(CFG.weights_dir, "*.pth")))\n',
            '    print(f"Found {len(model_paths)} model weights in {CFG.weights_dir}:")\n',
            '    for pth in model_paths:\n',
            '        print(f"  --> Loading: {os.path.basename(pth)}")\n',
            '        m = MultiViewDINOv2KneeModel(num_classes=num_classes)\n',
            '        m.load_state_dict(torch.load(pth, map_location=device))\n',
            '        m.to(device)\n',
            '        m.eval()\n',
            '        models.append(m)\n',
            '        \n',
            '    if not models:\n',
            '        print("⚠️ No .pth model weights found! Initializing fallback model.")\n',
            '        fallback_m = MultiViewDINOv2KneeModel(num_classes=num_classes).to(device)\n',
            '        fallback_m.eval()\n',
            '        models.append(fallback_m)\n',
            '        \n',
            '    # 3. Predict with Multi-Fold Averaging & TTA\n',
            '    all_study_ids = []\n',
            '    all_preds = []\n',
            '    \n',
            '    with torch.no_grad():\n',
            '        for images, study_ids in tqdm(dataloader, desc="Predicting"):\n',
            '            images = images.to(device)\n',
            '            batch_preds = torch.zeros((images.shape[0], num_classes), device=device)\n',
            '            \n',
            '            for m in models:\n',
            '                # Standard pass\n',
            '                p = torch.sigmoid(m(images))\n',
            '                \n',
            '                if CFG.use_tta:\n',
            '                    # Subtle intensity flip TTA\n',
            '                    p_tta = torch.sigmoid(m(images * 0.95))\n',
            '                    p = 0.5 * (p + p_tta)\n',
            '                    \n',
            '                batch_preds += p\n',
            '                \n',
            '            batch_preds /= len(models)\n',
            '            all_study_ids.extend(study_ids)\n',
            '            all_preds.append(batch_preds.cpu().numpy())\n',
            '            \n',
            '    all_preds = np.vstack(all_preds)\n',
            '    pred_df = pd.DataFrame(all_preds, columns=CFG.target_cols)\n',
            '    pred_df["StudyInstanceUID"] = all_study_ids\n',
            '    \n',
            '    # 4. Strictly Align with sample_submission.csv format\n',
            '    submission_df = sample_sub[["StudyInstanceUID"]].merge(pred_df, on="StudyInstanceUID", how="left")\n',
            '    submission_df = submission_df.fillna(0.5)\n',
            '    \n',
            '    # Ensure exact column structure\n',
            '    final_cols = ["StudyInstanceUID"] + [c for c in CFG.target_cols if c in sample_sub.columns or c != "StudyInstanceUID"]\n',
            '    submission_df = submission_df[final_cols]\n',
            '    \n',
            '    submission_df.to_csv("submission.csv", index=False)\n',
            '    print(f"\\n✅ Final submission.csv generated: {submission_df.shape}")\n',
            '    return submission_df\n',
            '\n',
            'if __name__ == "__main__":\n',
            '    sub = run_multiview_inference()\n',
            '    display(sub.head(10))\n'
        ]
    }
]

notebook = {
    'cells': cells,
    'metadata': {
        'kernelspec': {
            'display_name': 'Python 3',
            'language': 'python',
            'name': 'python3'
        }
    },
    'nbformat': 4,
    'nbformat_minor': 5
}

os.makedirs('notebooks', exist_ok=True)
with open('notebooks/RSNA_Knee_MultiView_DINOv2_Inference.ipynb', 'w') as f:
    json.dump(notebook, f, indent=2)

print("RSNA_Knee_MultiView_DINOv2_Inference.ipynb created successfully!")
